[package]
name = "lw-config"
version.workspace = true
edition.workspace = true

[dependencies]
serde.workspace = true
toml.workspace = true
dirs.workspace = true
tracing.workspace = true
anyhow.workspace = true
thiserror.workspace = true
