[package]
name = "lw-config"
version.workspace = true
edition.workspace = true

[dependencies]
serde.workspace = true
toml.workspace = true
dirs.workspace = true
anyhow.workspace = true

[dev-dependencies]
tempfile = "3"
