[package]
name = "lw-pty"
version.workspace = true
edition.workspace = true

[dependencies]
portable-pty.workspace = true
tokio.workspace = true
tracing.workspace = true
uuid.workspace = true
anyhow.workspace = true
thiserror.workspace = true
libc = "0.2"
