tasks:
  typecheck:
    command: 'tsc --noEmit'
    inputs:
      - '@group(sources)'
      - '@group(configs)'
    options:
      envFile: '/.env'

  lint:
    command: 'biome check .'
    inputs:
      - '@group(sources)'
    options:
      envFile: '/.env'
